#!/bin/bash

_header(){
	echo -e "DOMAIN,SCORE_CHECKS,SCORE_UPSTREAM,SCORE_UPSTREAMCHECK,SCORE_TRUST,SCORE_TOPKEYWORDS,SCORE_SEARCH,SCORE_PAGEVIEWS,SCORE_YEARS,SCORE_PRIVACY,SCORE_BOUNCERATE,ADMIN_CITY,ADMIN_COUNTRY,ALEXA_BOUNCERATE,ALEXA_INLINKS,ALEXA_LOADSPEED,ALEXA_PAGEVIEWS,ALEXA_RANK,ALEXA_SEARCHVISITS,ALEXA_TIMEONSITE,ALEXA_TOPCOUNTRIES,ALEXA_TOPKEYWORDS,ALEXA_UPSTREAM1,ALEXA_UPSTREAM1N,ALEXA_UPSTREAM2,ALEXA_UPSTREAM2N,ALEXA_UPSTREAM3,ALEXA_UPSTREAM3N,ALEXA_UPSTREAM4,ALEXA_UPSTREAM4N,ALEXA_UPSTREAM5,ALEXA_UPSTREAM5N,CHECKS_TOTAL,CHECK_FALSE,CHECK_TRUE,TOP5_UPSTREAM,WHOIS_PRIVACY,WHOIS_YEARS,WOT_CHILDSAFETY,WOT_TRUST" >> sitemind_signals.csv
	
}

_entry(){
	echo -e "$DOMAIN,$SCORE_CHECKS,$SCORE_UPSTREAM,$SCORE_UPSTREAMCHECK,$SCORE_TRUST,$SCORE_TOPKEYWORDS,$SCORE_SEARCH,$SCORE_PAGEVIEWS,$SCORE_YEARS,$SCORE_PRIVACY,$SCORE_BOUNCERATE,$ADMIN_CITY,$ADMIN_COUNTRY,$ALEXA_BOUNCERATE,$ALEXA_INLINKS,$ALEXA_LOADSPEED,$ALEXA_PAGEVIEWS,$ALEXA_RANK,$ALEXA_SEARCHVISITS,$ALEXA_TIMEONSITE,$ALEXA_TOPCOUNTRIES,$ALEXA_TOPKEYWORDS,$ALEXA_UPSTREAM1,$ALEXA_UPSTREAM1N,$ALEXA_UPSTREAM2,$ALEXA_UPSTREAM2N,$ALEXA_UPSTREAM3,$ALEXA_UPSTREAM3N,$ALEXA_UPSTREAM4,$ALEXA_UPSTREAM4N,$ALEXA_UPSTREAM5,$ALEXA_UPSTREAM5N,$CHECKS_TOTAL,$CHECK_FALSE,$CHECK_TRUE,$TOP5_UPSTREAM,$WHOIS_PRIVACY,$WHOIS_YEARS,$WOT_CHILDSAFETY,$WOT_TRUST" >> sitemind_signals.csv
}


sort -u env.bash > for_export.bash

source for_export.bash

if [ -f sitemind_signals.csv ] ; 
then 
	_entry
else
	_header
	_entry
fi	
